// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        kotlinVersion = '2.0.21'
        compileSdkVersion = 35
        minSdkVersion = 26
        targetSdkVersion = 35
        javaCompatibility = "17"

        timberVersion = '5.0.1'
        appCompatVersion = '1.7.0'
        daggerVersion = '2.55'
        coreKtxVersion = "1.16.0"
        prefKtxVersion = "1.2.1"
    }

    repositories {
        google()
        maven { url 'https://plugins.gradle.org/m2/' }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.9.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://plugins.gradle.org/m2/' }
    }
    group = 'org.tvheadend.tvhclientng'
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
